<?php

use Illuminate\Database\Seeder;

class MunicipalityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /* MUNICIPIOS */
		App\Municipality::create(array( 'id' => 1, 'state_id' => 1, 'municipality'=> 'Alto Orinoco'  ));
		App\Municipality::create(array( 'id' => 2, 'state_id' => 1, 'municipality'=> 'Atabapo'  ));
		App\Municipality::create(array( 'id' => 3, 'state_id' => 1, 'municipality'=> 'Atures'  ));
		App\Municipality::create(array( 'id' => 4, 'state_id' => 1, 'municipality'=> 'Autana'  ));
		App\Municipality::create(array( 'id' => 5, 'state_id' => 1, 'municipality'=> 'Manapiare'  ));
		App\Municipality::create(array( 'id' => 6, 'state_id' => 1, 'municipality'=> 'Maroa'  ));
		App\Municipality::create(array( 'id' => 7, 'state_id' => 1, 'municipality'=> 'Río Negro'  ));
		App\Municipality::create(array( 'id' => 8, 'state_id' => 2, 'municipality'=> 'Anaco'  ));
		App\Municipality::create(array( 'id' => 9, 'state_id' => 2, 'municipality'=> 'Aragua'  ));
		App\Municipality::create(array( 'id' => 10, 'state_id' => 2, 'municipality'=> 'Manuel Ezequiel Bruzual'  ));
		App\Municipality::create(array( 'id' => 11, 'state_id' => 2, 'municipality'=> 'Diego Bautista Urbaneja'  ));
		App\Municipality::create(array( 'id' => 12, 'state_id' => 2, 'municipality'=> 'Fernando Peñalver'  ));
		App\Municipality::create(array( 'id' => 13, 'state_id' => 2, 'municipality'=> 'Francisco Del Carmen Carvajal'  ));
		App\Municipality::create(array( 'id' => 14, 'state_id' => 2, 'municipality'=> 'General Sir Arthur McGregor'  ));
		App\Municipality::create(array( 'id' => 15, 'state_id' => 2, 'municipality'=> 'Guanta'  ));
		App\Municipality::create(array( 'id' => 16, 'state_id' => 2, 'municipality'=> 'Independencia'  ));
		App\Municipality::create(array( 'id' => 17, 'state_id' => 2, 'municipality'=> 'José Gregorio Monagas'  ));
		App\Municipality::create(array( 'id' => 18, 'state_id' => 2, 'municipality'=> 'Juan Antonio Sotillo'  ));
		App\Municipality::create(array( 'id' => 19, 'state_id' => 2, 'municipality'=> 'Juan Manuel Cajigal'  ));
		App\Municipality::create(array( 'id' => 20, 'state_id' => 2, 'municipality'=> 'Libertad'  ));
		App\Municipality::create(array( 'id' => 21, 'state_id' => 2, 'municipality'=> 'Francisco de Miranda'  ));
		App\Municipality::create(array( 'id' => 22, 'state_id' => 2, 'municipality'=> 'Pedro María Freites'  ));
		App\Municipality::create(array( 'id' => 23, 'state_id' => 2, 'municipality'=> 'Píritu'  ));
		App\Municipality::create(array( 'id' => 24, 'state_id' => 2, 'municipality'=> 'San José de Guanipa'  ));
		App\Municipality::create(array( 'id' => 25, 'state_id' => 2, 'municipality'=> 'San Juan de Capistrano'  ));
		App\Municipality::create(array( 'id' => 26, 'state_id' => 2, 'municipality'=> 'Santa Ana'  ));
		App\Municipality::create(array( 'id' => 27, 'state_id' => 2, 'municipality'=> 'Simón Bolívar'  ));
		App\Municipality::create(array( 'id' => 28, 'state_id' => 2, 'municipality'=> 'Simón Rodríguez'  ));
		App\Municipality::create(array( 'id' => 29, 'state_id' => 3, 'municipality'=> 'Achaguas'  ));
		App\Municipality::create(array( 'id' => 30, 'state_id' => 3, 'municipality'=> 'Biruaca'  ));
		App\Municipality::create(array( 'id' => 31, 'state_id' => 3, 'municipality'=> 'Muñóz'  ));
		App\Municipality::create(array( 'id' => 32, 'state_id' => 3, 'municipality'=> 'Páez'  ));
		App\Municipality::create(array( 'id' => 33, 'state_id' => 3, 'municipality'=> 'Pedro Camejo'  ));
		App\Municipality::create(array( 'id' => 34, 'state_id' => 3, 'municipality'=> 'Rómulo Gallegos'  ));
		App\Municipality::create(array( 'id' => 35, 'state_id' => 3, 'municipality'=> 'San Fernando'  ));
		App\Municipality::create(array( 'id' => 36, 'state_id' => 4, 'municipality'=> 'Atanasio Girardot'  ));
		App\Municipality::create(array( 'id' => 37, 'state_id' => 4, 'municipality'=> 'Bolívar'  ));
		App\Municipality::create(array( 'id' => 38, 'state_id' => 4, 'municipality'=> 'Camatagua'  ));
		App\Municipality::create(array( 'id' => 39, 'state_id' => 4, 'municipality'=> 'Francisco Linares Alcántara'  ));
		App\Municipality::create(array( 'id' => 40, 'state_id' => 4, 'municipality'=> 'José Ángel Lamas'  ));
		App\Municipality::create(array( 'id' => 41, 'state_id' => 4, 'municipality'=> 'José Félix Ribas'  ));
		App\Municipality::create(array( 'id' => 42, 'state_id' => 4, 'municipality'=> 'José Rafael Revenga'  ));
		App\Municipality::create(array( 'id' => 43, 'state_id' => 4, 'municipality'=> 'Libertador'  ));
		App\Municipality::create(array( 'id' => 44, 'state_id' => 4, 'municipality'=> 'Mario Briceño Iragorry'  ));
		App\Municipality::create(array( 'id' => 45, 'state_id' => 4, 'municipality'=> 'Ocumare de la Costa de Oro'  ));
		App\Municipality::create(array( 'id' => 46, 'state_id' => 4, 'municipality'=> 'San Casimiro'  ));
		App\Municipality::create(array( 'id' => 47, 'state_id' => 4, 'municipality'=> 'San Sebastián'  ));
		App\Municipality::create(array( 'id' => 48, 'state_id' => 4, 'municipality'=> 'Santiago Mariño'  ));
		App\Municipality::create(array( 'id' => 49, 'state_id' => 4, 'municipality'=> 'Santos Michelena'  ));
		App\Municipality::create(array( 'id' => 50, 'state_id' => 4, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 51, 'state_id' => 4, 'municipality'=> 'Tovar'  ));
		App\Municipality::create(array( 'id' => 52, 'state_id' => 4, 'municipality'=> 'Urdaneta'  ));
		App\Municipality::create(array( 'id' => 53, 'state_id' => 4, 'municipality'=> 'Zamora'  ));
		App\Municipality::create(array( 'id' => 54, 'state_id' => 5, 'municipality'=> 'Alberto Arvelo Torrealba'  ));
		App\Municipality::create(array( 'id' => 55, 'state_id' => 5, 'municipality'=> 'Andrés Eloy Blanco'  ));
		App\Municipality::create(array( 'id' => 56, 'state_id' => 5, 'municipality'=> 'Antonio José de Sucre'  ));
		App\Municipality::create(array( 'id' => 57, 'state_id' => 5, 'municipality'=> 'Arismendi'  ));
		App\Municipality::create(array( 'id' => 58, 'state_id' => 5, 'municipality'=> 'Barinas'  ));
		App\Municipality::create(array( 'id' => 59, 'state_id' => 5, 'municipality'=> 'Bolívar'  ));
		App\Municipality::create(array( 'id' => 60, 'state_id' => 5, 'municipality'=> 'Cruz Paredes'  ));
		App\Municipality::create(array( 'id' => 61, 'state_id' => 5, 'municipality'=> 'Ezequiel Zamora'  ));
		App\Municipality::create(array( 'id' => 62, 'state_id' => 5, 'municipality'=> 'Obispos'  ));
		App\Municipality::create(array( 'id' => 63, 'state_id' => 5, 'municipality'=> 'Pedraza'  ));
		App\Municipality::create(array( 'id' => 64, 'state_id' => 5, 'municipality'=> 'Rojas'  ));
		App\Municipality::create(array( 'id' => 65, 'state_id' => 5, 'municipality'=> 'Sosa'  ));
		App\Municipality::create(array( 'id' => 66, 'state_id' => 6, 'municipality'=> 'Caroní'  ));
		App\Municipality::create(array( 'id' => 67, 'state_id' => 6, 'municipality'=> 'Cedeño'  ));
		App\Municipality::create(array( 'id' => 68, 'state_id' => 6, 'municipality'=> 'El Callao'  ));
		App\Municipality::create(array( 'id' => 69, 'state_id' => 6, 'municipality'=> 'Gran Sabana'  ));
		App\Municipality::create(array( 'id' => 70, 'state_id' => 6, 'municipality'=> 'Heres'  ));
		App\Municipality::create(array( 'id' => 71, 'state_id' => 6, 'municipality'=> 'Piar'  ));
		App\Municipality::create(array( 'id' => 72, 'state_id' => 6, 'municipality'=> 'Angostura (Raúl Leoni)'  ));
		App\Municipality::create(array( 'id' => 73, 'state_id' => 6, 'municipality'=> 'Roscio'  ));
		App\Municipality::create(array( 'id' => 74, 'state_id' => 6, 'municipality'=> 'Sifontes'  ));
		App\Municipality::create(array( 'id' => 75, 'state_id' => 6, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 76, 'state_id' => 6, 'municipality'=> 'Padre Pedro Chien'  ));
		App\Municipality::create(array( 'id' => 77, 'state_id' => 7, 'municipality'=> 'Bejuma'  ));
		App\Municipality::create(array( 'id' => 78, 'state_id' => 7, 'municipality'=> 'Carlos Arvelo'  ));
		App\Municipality::create(array( 'id' => 79, 'state_id' => 7, 'municipality'=> 'Diego Ibarra'  ));
		App\Municipality::create(array( 'id' => 80, 'state_id' => 7, 'municipality'=> 'Guacara'  ));
		App\Municipality::create(array( 'id' => 81, 'state_id' => 7, 'municipality'=> 'Juan José Mora'  ));
		App\Municipality::create(array( 'id' => 82, 'state_id' => 7, 'municipality'=> 'Libertador'  ));
		App\Municipality::create(array( 'id' => 83, 'state_id' => 7, 'municipality'=> 'Los Guayos'  ));
		App\Municipality::create(array( 'id' => 84, 'state_id' => 7, 'municipality'=> 'Miranda'  ));
		App\Municipality::create(array( 'id' => 85, 'state_id' => 7, 'municipality'=> 'Montalbán'  ));
		App\Municipality::create(array( 'id' => 86, 'state_id' => 7, 'municipality'=> 'Naguanagua'  ));
		App\Municipality::create(array( 'id' => 87, 'state_id' => 7, 'municipality'=> 'Puerto Cabello'  ));
		App\Municipality::create(array( 'id' => 88, 'state_id' => 7, 'municipality'=> 'San Diego'  ));
		App\Municipality::create(array( 'id' => 89, 'state_id' => 7, 'municipality'=> 'San Joaquín'  ));
		App\Municipality::create(array( 'id' => 90, 'state_id' => 7, 'municipality'=> 'Valencia'  ));
		App\Municipality::create(array( 'id' => 91, 'state_id' => 8, 'municipality'=> 'Anzoátegui'  ));
		App\Municipality::create(array( 'id' => 92, 'state_id' => 8, 'municipality'=> 'Tinaquillo'  ));
		App\Municipality::create(array( 'id' => 93, 'state_id' => 8, 'municipality'=> 'Girardot'  ));
		App\Municipality::create(array( 'id' => 94, 'state_id' => 8, 'municipality'=> 'Lima Blanco'  ));
		App\Municipality::create(array( 'id' => 95, 'state_id' => 8, 'municipality'=> 'Pao de San Juan Bautista'  ));
		App\Municipality::create(array( 'id' => 96, 'state_id' => 8, 'municipality'=> 'Ricaurte'  ));
		App\Municipality::create(array( 'id' => 97, 'state_id' => 8, 'municipality'=> 'Rómulo Gallegos'  ));
		App\Municipality::create(array( 'id' => 98, 'state_id' => 8, 'municipality'=> 'San Carlos'  ));
		App\Municipality::create(array( 'id' => 99, 'state_id' => 8, 'municipality'=> 'Tinaco'  ));
		App\Municipality::create(array( 'id' => 100, 'state_id' => 9, 'municipality'=> 'Antonio Díaz'  ));
		App\Municipality::create(array( 'id' => 101, 'state_id' => 9, 'municipality'=> 'Casacoima'  ));
		App\Municipality::create(array( 'id' => 102, 'state_id' => 9, 'municipality'=> 'Pedernales'  ));
		App\Municipality::create(array( 'id' => 103, 'state_id' => 9, 'municipality'=> 'Tucupita'  ));
		App\Municipality::create(array( 'id' => 104, 'state_id' => 10, 'municipality'=> 'Acosta'  ));
		App\Municipality::create(array( 'id' => 105, 'state_id' => 10, 'municipality'=> 'Bolívar'  ));
		App\Municipality::create(array( 'id' => 106, 'state_id' => 10, 'municipality'=> 'Buchivacoa'  ));
		App\Municipality::create(array( 'id' => 107, 'state_id' => 10, 'municipality'=> 'Cacique Manaure'  ));
		App\Municipality::create(array( 'id' => 108, 'state_id' => 10, 'municipality'=> 'Carirubana'  ));
		App\Municipality::create(array( 'id' => 109, 'state_id' => 10, 'municipality'=> 'Colina'  ));
		App\Municipality::create(array( 'id' => 110, 'state_id' => 10, 'municipality'=> 'Dabajuro'  ));
		App\Municipality::create(array( 'id' => 111, 'state_id' => 10, 'municipality'=> 'Democracia'  ));
		App\Municipality::create(array( 'id' => 112, 'state_id' => 10, 'municipality'=> 'Falcón'  ));
		App\Municipality::create(array( 'id' => 113, 'state_id' => 10, 'municipality'=> 'Federación'  ));
		App\Municipality::create(array( 'id' => 114, 'state_id' => 10, 'municipality'=> 'Jacura'  ));
		App\Municipality::create(array( 'id' => 115, 'state_id' => 10, 'municipality'=> 'José Laurencio Silva'  ));
		App\Municipality::create(array( 'id' => 116, 'state_id' => 10, 'municipality'=> 'Los Taques'  ));
		App\Municipality::create(array( 'id' => 117, 'state_id' => 10, 'municipality'=> 'Mauroa'  ));
		App\Municipality::create(array( 'id' => 118, 'state_id' => 10, 'municipality'=> 'Miranda'  ));
		App\Municipality::create(array( 'id' => 119, 'state_id' => 10, 'municipality'=> 'Monseñor Iturriza'  ));
		App\Municipality::create(array( 'id' => 120, 'state_id' => 10, 'municipality'=> 'Palmasola'  ));
		App\Municipality::create(array( 'id' => 121, 'state_id' => 10, 'municipality'=> 'Petit'  ));
		App\Municipality::create(array( 'id' => 122, 'state_id' => 10, 'municipality'=> 'Píritu'  ));
		App\Municipality::create(array( 'id' => 123, 'state_id' => 10, 'municipality'=> 'San Francisco'  ));
		App\Municipality::create(array( 'id' => 124, 'state_id' => 10, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 125, 'state_id' => 10, 'municipality'=> 'Tocópero'  ));
		App\Municipality::create(array( 'id' => 126, 'state_id' => 10, 'municipality'=> 'Unión'  ));
		App\Municipality::create(array( 'id' => 127, 'state_id' => 10, 'municipality'=> 'Urumaco'  ));
		App\Municipality::create(array( 'id' => 128, 'state_id' => 10, 'municipality'=> 'Zamora'  ));
		App\Municipality::create(array( 'id' => 129, 'state_id' => 11, 'municipality'=> 'Camaguán'  ));
		App\Municipality::create(array( 'id' => 130, 'state_id' => 11, 'municipality'=> 'Chaguaramas'  ));
		App\Municipality::create(array( 'id' => 131, 'state_id' => 11, 'municipality'=> 'El Socorro'  ));
		App\Municipality::create(array( 'id' => 132, 'state_id' => 11, 'municipality'=> 'José Félix Ribas'  ));
		App\Municipality::create(array( 'id' => 133, 'state_id' => 11, 'municipality'=> 'José Tadeo Monagas'  ));
		App\Municipality::create(array( 'id' => 134, 'state_id' => 11, 'municipality'=> 'Juan Germán Roscio'  ));
		App\Municipality::create(array( 'id' => 135, 'state_id' => 11, 'municipality'=> 'Julián Mellado'  ));
		App\Municipality::create(array( 'id' => 136, 'state_id' => 11, 'municipality'=> 'Las Mercedes'  ));
		App\Municipality::create(array( 'id' => 137, 'state_id' => 11, 'municipality'=> 'Leonardo Infante'  ));
		App\Municipality::create(array( 'id' => 138, 'state_id' => 11, 'municipality'=> 'Pedro Zaraza'  ));
		App\Municipality::create(array( 'id' => 139, 'state_id' => 11, 'municipality'=> 'Ortíz'  ));
		App\Municipality::create(array( 'id' => 140, 'state_id' => 11, 'municipality'=> 'San Gerónimo de Guayabal'  ));
		App\Municipality::create(array( 'id' => 141, 'state_id' => 11, 'municipality'=> 'San José de Guaribe'  ));
		App\Municipality::create(array( 'id' => 142, 'state_id' => 11, 'municipality'=> 'Santa María de Ipire'  ));
		App\Municipality::create(array( 'id' => 143, 'state_id' => 11, 'municipality'=> 'Sebastián Francisco de Miranda'  ));
		App\Municipality::create(array( 'id' => 144, 'state_id' => 12, 'municipality'=> 'Andrés Eloy Blanco'  ));
		App\Municipality::create(array( 'id' => 145, 'state_id' => 12, 'municipality'=> 'Crespo'  ));
		App\Municipality::create(array( 'id' => 146, 'state_id' => 12, 'municipality'=> 'Iribarren'  ));
		App\Municipality::create(array( 'id' => 147, 'state_id' => 12, 'municipality'=> 'Jiménez'  ));
		App\Municipality::create(array( 'id' => 148, 'state_id' => 12, 'municipality'=> 'Morán'  ));
		App\Municipality::create(array( 'id' => 149, 'state_id' => 12, 'municipality'=> 'Palavecino'  ));
		App\Municipality::create(array( 'id' => 150, 'state_id' => 12, 'municipality'=> 'Simón Planas'  ));
		App\Municipality::create(array( 'id' => 151, 'state_id' => 12, 'municipality'=> 'Torres'  ));
		App\Municipality::create(array( 'id' => 152, 'state_id' => 12, 'municipality'=> 'Urdaneta'  ));
		App\Municipality::create(array( 'id' => 179, 'state_id' => 13, 'municipality'=> 'Alberto Adriani'  ));
		App\Municipality::create(array( 'id' => 180, 'state_id' => 13, 'municipality'=> 'Andrés Bello'  ));
		App\Municipality::create(array( 'id' => 181, 'state_id' => 13, 'municipality'=> 'Antonio Pinto Salinas'  ));
		App\Municipality::create(array( 'id' => 182, 'state_id' => 13, 'municipality'=> 'Aricagua'  ));
		App\Municipality::create(array( 'id' => 183, 'state_id' => 13, 'municipality'=> 'Arzobispo Chacón'  ));
		App\Municipality::create(array( 'id' => 184, 'state_id' => 13, 'municipality'=> 'Campo Elías'  ));
		App\Municipality::create(array( 'id' => 185, 'state_id' => 13, 'municipality'=> 'Caracciolo Parra Olmedo'  ));
		App\Municipality::create(array( 'id' => 186, 'state_id' => 13, 'municipality'=> 'Cardenal Quintero'  ));
		App\Municipality::create(array( 'id' => 187, 'state_id' => 13, 'municipality'=> 'Guaraque'  ));
		App\Municipality::create(array( 'id' => 188, 'state_id' => 13, 'municipality'=> 'Julio César Salas'  ));
		App\Municipality::create(array( 'id' => 189, 'state_id' => 13, 'municipality'=> 'Justo Briceño'  ));
		App\Municipality::create(array( 'id' => 190, 'state_id' => 13, 'municipality'=> 'Libertador'  ));
		App\Municipality::create(array( 'id' => 191, 'state_id' => 13, 'municipality'=> 'Miranda'  ));
		App\Municipality::create(array( 'id' => 192, 'state_id' => 13, 'municipality'=> 'Obispo Ramos de Lora'  ));
		App\Municipality::create(array( 'id' => 193, 'state_id' => 13, 'municipality'=> 'Padre Noguera'  ));
		App\Municipality::create(array( 'id' => 194, 'state_id' => 13, 'municipality'=> 'Pueblo Llano'  ));
		App\Municipality::create(array( 'id' => 195, 'state_id' => 13, 'municipality'=> 'Rangel'  ));
		App\Municipality::create(array( 'id' => 196, 'state_id' => 13, 'municipality'=> 'Rivas Dávila'  ));
		App\Municipality::create(array( 'id' => 197, 'state_id' => 13, 'municipality'=> 'Santos Marquina'  ));
		App\Municipality::create(array( 'id' => 198, 'state_id' => 13, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 199, 'state_id' => 13, 'municipality'=> 'Tovar'  ));
		App\Municipality::create(array( 'id' => 200, 'state_id' => 13, 'municipality'=> 'Tulio Febres Cordero'  ));
		App\Municipality::create(array( 'id' => 201, 'state_id' => 13, 'municipality'=> 'Zea'  ));
		App\Municipality::create(array( 'id' => 223, 'state_id' => 14, 'municipality'=> 'Acevedo'  ));
		App\Municipality::create(array( 'id' => 224, 'state_id' => 14, 'municipality'=> 'Andrés Bello'  ));
		App\Municipality::create(array( 'id' => 225, 'state_id' => 14, 'municipality'=> 'Baruta'  ));
		App\Municipality::create(array( 'id' => 226, 'state_id' => 14, 'municipality'=> 'Brión'  ));
		App\Municipality::create(array( 'id' => 227, 'state_id' => 14, 'municipality'=> 'Buroz'  ));
		App\Municipality::create(array( 'id' => 228, 'state_id' => 14, 'municipality'=> 'Carrizal'  ));
		App\Municipality::create(array( 'id' => 229, 'state_id' => 14, 'municipality'=> 'Chacao'  ));
		App\Municipality::create(array( 'id' => 230, 'state_id' => 14, 'municipality'=> 'Cristóbal Rojas'  ));
		App\Municipality::create(array( 'id' => 231, 'state_id' => 14, 'municipality'=> 'El Hatillo'  ));
		App\Municipality::create(array( 'id' => 232, 'state_id' => 14, 'municipality'=> 'Guaicaipuro'  ));
		App\Municipality::create(array( 'id' => 233, 'state_id' => 14, 'municipality'=> 'Independencia'  ));
		App\Municipality::create(array( 'id' => 234, 'state_id' => 14, 'municipality'=> 'Lander'  ));
		App\Municipality::create(array( 'id' => 235, 'state_id' => 14, 'municipality'=> 'Los Salias'  ));
		App\Municipality::create(array( 'id' => 236, 'state_id' => 14, 'municipality'=> 'Páez'  ));
		App\Municipality::create(array( 'id' => 237, 'state_id' => 14, 'municipality'=> 'Paz Castillo'  ));
		App\Municipality::create(array( 'id' => 238, 'state_id' => 14, 'municipality'=> 'Pedro Gual'  ));
		App\Municipality::create(array( 'id' => 239, 'state_id' => 14, 'municipality'=> 'Plaza'  ));
		App\Municipality::create(array( 'id' => 240, 'state_id' => 14, 'municipality'=> 'Simón Bolívar'  ));
		App\Municipality::create(array( 'id' => 241, 'state_id' => 14, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 242, 'state_id' => 14, 'municipality'=> 'Urdaneta'  ));
		App\Municipality::create(array( 'id' => 243, 'state_id' => 14, 'municipality'=> 'Zamora'  ));
		App\Municipality::create(array( 'id' => 258, 'state_id' => 15, 'municipality'=> 'Acosta'  ));
		App\Municipality::create(array( 'id' => 259, 'state_id' => 15, 'municipality'=> 'Aguasay'  ));
		App\Municipality::create(array( 'id' => 260, 'state_id' => 15, 'municipality'=> 'Bolívar'  ));
		App\Municipality::create(array( 'id' => 261, 'state_id' => 15, 'municipality'=> 'Caripe'  ));
		App\Municipality::create(array( 'id' => 262, 'state_id' => 15, 'municipality'=> 'Cedeño'  ));
		App\Municipality::create(array( 'id' => 263, 'state_id' => 15, 'municipality'=> 'Ezequiel Zamora'  ));
		App\Municipality::create(array( 'id' => 264, 'state_id' => 15, 'municipality'=> 'Libertador'  ));
		App\Municipality::create(array( 'id' => 265, 'state_id' => 15, 'municipality'=> 'Maturín'  ));
		App\Municipality::create(array( 'id' => 266, 'state_id' => 15, 'municipality'=> 'Piar'  ));
		App\Municipality::create(array( 'id' => 267, 'state_id' => 15, 'municipality'=> 'Punceres'  ));
		App\Municipality::create(array( 'id' => 268, 'state_id' => 15, 'municipality'=> 'Santa Bárbara'  ));
		App\Municipality::create(array( 'id' => 269, 'state_id' => 15, 'municipality'=> 'Sotillo'  ));
		App\Municipality::create(array( 'id' => 270, 'state_id' => 15, 'municipality'=> 'Uracoa'  ));
		App\Municipality::create(array( 'id' => 271, 'state_id' => 16, 'municipality'=> 'Antolín del Campo'  ));
		App\Municipality::create(array( 'id' => 272, 'state_id' => 16, 'municipality'=> 'Arismendi'  ));
		App\Municipality::create(array( 'id' => 273, 'state_id' => 16, 'municipality'=> 'García'  ));
		App\Municipality::create(array( 'id' => 274, 'state_id' => 16, 'municipality'=> 'Gómez'  ));
		App\Municipality::create(array( 'id' => 275, 'state_id' => 16, 'municipality'=> 'Maneiro'  ));
		App\Municipality::create(array( 'id' => 276, 'state_id' => 16, 'municipality'=> 'Marcano'  ));
		App\Municipality::create(array( 'id' => 277, 'state_id' => 16, 'municipality'=> 'Mariño'  ));
		App\Municipality::create(array( 'id' => 278, 'state_id' => 16, 'municipality'=> 'Península de Macanao'  ));
		App\Municipality::create(array( 'id' => 279, 'state_id' => 16, 'municipality'=> 'Tubores'  ));
		App\Municipality::create(array( 'id' => 280, 'state_id' => 16, 'municipality'=> 'Villalba'  ));
		App\Municipality::create(array( 'id' => 281, 'state_id' => 16, 'municipality'=> 'Díaz'  ));
		App\Municipality::create(array( 'id' => 282, 'state_id' => 17, 'municipality'=> 'Agua Blanca'  ));
		App\Municipality::create(array( 'id' => 283, 'state_id' => 17, 'municipality'=> 'Araure'  ));
		App\Municipality::create(array( 'id' => 284, 'state_id' => 17, 'municipality'=> 'Esteller'  ));
		App\Municipality::create(array( 'id' => 285, 'state_id' => 17, 'municipality'=> 'Guanare'  ));
		App\Municipality::create(array( 'id' => 286, 'state_id' => 17, 'municipality'=> 'Guanarito'  ));
		App\Municipality::create(array( 'id' => 287, 'state_id' => 17, 'municipality'=> 'Monseñor José Vicente de Unda'  ));
		App\Municipality::create(array( 'id' => 288, 'state_id' => 17, 'municipality'=> 'Ospino'  ));
		App\Municipality::create(array( 'id' => 289, 'state_id' => 17, 'municipality'=> 'Páez'  ));
		App\Municipality::create(array( 'id' => 290, 'state_id' => 17, 'municipality'=> 'Papelón'  ));
		App\Municipality::create(array( 'id' => 291, 'state_id' => 17, 'municipality'=> 'San Genaro de Boconoíto'  ));
		App\Municipality::create(array( 'id' => 292, 'state_id' => 17, 'municipality'=> 'San Rafael de Onoto'  ));
		App\Municipality::create(array( 'id' => 293, 'state_id' => 17, 'municipality'=> 'Santa Rosalía'  ));
		App\Municipality::create(array( 'id' => 294, 'state_id' => 17, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 295, 'state_id' => 17, 'municipality'=> 'Turén'  ));
		App\Municipality::create(array( 'id' => 296, 'state_id' => 18, 'municipality'=> 'Andrés Eloy Blanco'  ));
		App\Municipality::create(array( 'id' => 297, 'state_id' => 18, 'municipality'=> 'Andrés Mata'  ));
		App\Municipality::create(array( 'id' => 298, 'state_id' => 18, 'municipality'=> 'Arismendi'  ));
		App\Municipality::create(array( 'id' => 299, 'state_id' => 18, 'municipality'=> 'Benítez'  ));
		App\Municipality::create(array( 'id' => 300, 'state_id' => 18, 'municipality'=> 'Bermúdez'  ));
		App\Municipality::create(array( 'id' => 301, 'state_id' => 18, 'municipality'=> 'Bolívar'  ));
		App\Municipality::create(array( 'id' => 302, 'state_id' => 18, 'municipality'=> 'Cajigal'  ));
		App\Municipality::create(array( 'id' => 303, 'state_id' => 18, 'municipality'=> 'Cruz Salmerón Acosta'  ));
		App\Municipality::create(array( 'id' => 304, 'state_id' => 18, 'municipality'=> 'Libertador'  ));
		App\Municipality::create(array( 'id' => 305, 'state_id' => 18, 'municipality'=> 'Mariño'  ));
		App\Municipality::create(array( 'id' => 306, 'state_id' => 18, 'municipality'=> 'Mejía'  ));
		App\Municipality::create(array( 'id' => 307, 'state_id' => 18, 'municipality'=> 'Montes'  ));
		App\Municipality::create(array( 'id' => 308, 'state_id' => 18, 'municipality'=> 'Ribero'  ));
		App\Municipality::create(array( 'id' => 309, 'state_id' => 18, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 310, 'state_id' => 18, 'municipality'=> 'Valdéz'  ));
		App\Municipality::create(array( 'id' => 341, 'state_id' => 19, 'municipality'=> 'Andrés Bello'  ));
		App\Municipality::create(array( 'id' => 342, 'state_id' => 19, 'municipality'=> 'Antonio Rómulo Costa'  ));
		App\Municipality::create(array( 'id' => 343, 'state_id' => 19, 'municipality'=> 'Ayacucho'  ));
		App\Municipality::create(array( 'id' => 344, 'state_id' => 19, 'municipality'=> 'Bolívar'  ));
		App\Municipality::create(array( 'id' => 345, 'state_id' => 19, 'municipality'=> 'Cárdenas'  ));
		App\Municipality::create(array( 'id' => 346, 'state_id' => 19, 'municipality'=> 'Córdoba'  ));
		App\Municipality::create(array( 'id' => 347, 'state_id' => 19, 'municipality'=> 'Fernández Feo'  ));
		App\Municipality::create(array( 'id' => 348, 'state_id' => 19, 'municipality'=> 'Francisco de Miranda'  ));
		App\Municipality::create(array( 'id' => 349, 'state_id' => 19, 'municipality'=> 'García de Hevia'  ));
		App\Municipality::create(array( 'id' => 350, 'state_id' => 19, 'municipality'=> 'Guásimos'  ));
		App\Municipality::create(array( 'id' => 351, 'state_id' => 19, 'municipality'=> 'Independencia'  ));
		App\Municipality::create(array( 'id' => 352, 'state_id' => 19, 'municipality'=> 'Jáuregui'  ));
		App\Municipality::create(array( 'id' => 353, 'state_id' => 19, 'municipality'=> 'José María Vargas'  ));
		App\Municipality::create(array( 'id' => 354, 'state_id' => 19, 'municipality'=> 'Junín'  ));
		App\Municipality::create(array( 'id' => 355, 'state_id' => 19, 'municipality'=> 'Libertad'  ));
		App\Municipality::create(array( 'id' => 356, 'state_id' => 19, 'municipality'=> 'Libertador'  ));
		App\Municipality::create(array( 'id' => 357, 'state_id' => 19, 'municipality'=> 'Lobatera'  ));
		App\Municipality::create(array( 'id' => 358, 'state_id' => 19, 'municipality'=> 'Michelena'  ));
		App\Municipality::create(array( 'id' => 359, 'state_id' => 19, 'municipality'=> 'Panamericano'  ));
		App\Municipality::create(array( 'id' => 360, 'state_id' => 19, 'municipality'=> 'Pedro María Ureña'  ));
		App\Municipality::create(array( 'id' => 361, 'state_id' => 19, 'municipality'=> 'Rafael Urdaneta'  ));
		App\Municipality::create(array( 'id' => 362, 'state_id' => 19, 'municipality'=> 'Samuel Darío Maldonado'  ));
		App\Municipality::create(array( 'id' => 363, 'state_id' => 19, 'municipality'=> 'San Cristóbal'  ));
		App\Municipality::create(array( 'id' => 364, 'state_id' => 19, 'municipality'=> 'Seboruco'  ));
		App\Municipality::create(array( 'id' => 365, 'state_id' => 19, 'municipality'=> 'Simón Rodríguez'  ));
		App\Municipality::create(array( 'id' => 366, 'state_id' => 19, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 367, 'state_id' => 19, 'municipality'=> 'Torbes'  ));
		App\Municipality::create(array( 'id' => 368, 'state_id' => 19, 'municipality'=> 'Uribante'  ));
		App\Municipality::create(array( 'id' => 369, 'state_id' => 19, 'municipality'=> 'San Judas Tadeo'  ));
		App\Municipality::create(array( 'id' => 370, 'state_id' => 20, 'municipality'=> 'Andrés Bello'  ));
		App\Municipality::create(array( 'id' => 371, 'state_id' => 20, 'municipality'=> 'Boconó'  ));
		App\Municipality::create(array( 'id' => 372, 'state_id' => 20, 'municipality'=> 'Bolívar'  ));
		App\Municipality::create(array( 'id' => 373, 'state_id' => 20, 'municipality'=> 'Candelaria'  ));
		App\Municipality::create(array( 'id' => 374, 'state_id' => 20, 'municipality'=> 'Carache'  ));
		App\Municipality::create(array( 'id' => 375, 'state_id' => 20, 'municipality'=> 'Escuque'  ));
		App\Municipality::create(array( 'id' => 376, 'state_id' => 20, 'municipality'=> 'José Felipe Márquez Cañizalez'  ));
		App\Municipality::create(array( 'id' => 377, 'state_id' => 20, 'municipality'=> 'Juan Vicente Campos Elías'  ));
		App\Municipality::create(array( 'id' => 378, 'state_id' => 20, 'municipality'=> 'La Ceiba'  ));
		App\Municipality::create(array( 'id' => 379, 'state_id' => 20, 'municipality'=> 'Miranda'  ));
		App\Municipality::create(array( 'id' => 380, 'state_id' => 20, 'municipality'=> 'Monte Carmelo'  ));
		App\Municipality::create(array( 'id' => 381, 'state_id' => 20, 'municipality'=> 'Motatán'  ));
		App\Municipality::create(array( 'id' => 382, 'state_id' => 20, 'municipality'=> 'Pampán'  ));
		App\Municipality::create(array( 'id' => 383, 'state_id' => 20, 'municipality'=> 'Pampanito'  ));
		App\Municipality::create(array( 'id' => 384, 'state_id' => 20, 'municipality'=> 'Rafael Rangel'  ));
		App\Municipality::create(array( 'id' => 385, 'state_id' => 20, 'municipality'=> 'San Rafael de Carvajal'  ));
		App\Municipality::create(array( 'id' => 386, 'state_id' => 20, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 387, 'state_id' => 20, 'municipality'=> 'Trujillo'  ));
		App\Municipality::create(array( 'id' => 388, 'state_id' => 20, 'municipality'=> 'Urdaneta'  ));
		App\Municipality::create(array( 'id' => 389, 'state_id' => 20, 'municipality'=> 'Valera'  ));
		App\Municipality::create(array( 'id' => 390, 'state_id' => 21, 'municipality'=> 'Vargas'  ));
		App\Municipality::create(array( 'id' => 391, 'state_id' => 22, 'municipality'=> 'Arístides Bastidas'  ));
		App\Municipality::create(array( 'id' => 392, 'state_id' => 22, 'municipality'=> 'Bolívar'  ));
		App\Municipality::create(array( 'id' => 407, 'state_id' => 22, 'municipality'=> 'Bruzual'  ));
		App\Municipality::create(array( 'id' => 408, 'state_id' => 22, 'municipality'=> 'Cocorote'  ));
		App\Municipality::create(array( 'id' => 409, 'state_id' => 22, 'municipality'=> 'Independencia'  ));
		App\Municipality::create(array( 'id' => 410, 'state_id' => 22, 'municipality'=> 'José Antonio Páez'  ));
		App\Municipality::create(array( 'id' => 411, 'state_id' => 22, 'municipality'=> 'La Trinidad'  ));
		App\Municipality::create(array( 'id' => 412, 'state_id' => 22, 'municipality'=> 'Manuel Monge'  ));
		App\Municipality::create(array( 'id' => 413, 'state_id' => 22, 'municipality'=> 'Nirgua'  ));
		App\Municipality::create(array( 'id' => 414, 'state_id' => 22, 'municipality'=> 'Peña'  ));
		App\Municipality::create(array( 'id' => 415, 'state_id' => 22, 'municipality'=> 'San Felipe'  ));
		App\Municipality::create(array( 'id' => 416, 'state_id' => 22, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 417, 'state_id' => 22, 'municipality'=> 'Urachiche'  ));
		App\Municipality::create(array( 'id' => 418, 'state_id' => 22, 'municipality'=> 'José Joaquín Veroes'  ));
		App\Municipality::create(array( 'id' => 441, 'state_id' => 23, 'municipality'=> 'Almirante Padilla'  ));
		App\Municipality::create(array( 'id' => 442, 'state_id' => 23, 'municipality'=> 'Baralt'  ));
		App\Municipality::create(array( 'id' => 443, 'state_id' => 23, 'municipality'=> 'Cabimas'  ));
		App\Municipality::create(array( 'id' => 444, 'state_id' => 23, 'municipality'=> 'Catatumbo'  ));
		App\Municipality::create(array( 'id' => 445, 'state_id' => 23, 'municipality'=> 'Colón'  ));
		App\Municipality::create(array( 'id' => 446, 'state_id' => 23, 'municipality'=> 'Francisco Javier Pulgar'  ));
		App\Municipality::create(array( 'id' => 447, 'state_id' => 23, 'municipality'=> 'Páez'  ));
		App\Municipality::create(array( 'id' => 448, 'state_id' => 23, 'municipality'=> 'Jesús Enrique Losada'  ));
		App\Municipality::create(array( 'id' => 449, 'state_id' => 23, 'municipality'=> 'Jesús María Semprún'  ));
		App\Municipality::create(array( 'id' => 450, 'state_id' => 23, 'municipality'=> 'La Cañada de Urdaneta'  ));
		App\Municipality::create(array( 'id' => 451, 'state_id' => 23, 'municipality'=> 'Lagunillas'  ));
		App\Municipality::create(array( 'id' => 452, 'state_id' => 23, 'municipality'=> 'Machiques de Perijá'  ));
		App\Municipality::create(array( 'id' => 453, 'state_id' => 23, 'municipality'=> 'Mara'  ));
		App\Municipality::create(array( 'id' => 454, 'state_id' => 23, 'municipality'=> 'Maracaibo'  ));
		App\Municipality::create(array( 'id' => 455, 'state_id' => 23, 'municipality'=> 'Miranda'  ));
		App\Municipality::create(array( 'id' => 456, 'state_id' => 23, 'municipality'=> 'Rosario de Perijá'  ));
		App\Municipality::create(array( 'id' => 457, 'state_id' => 23, 'municipality'=> 'San Francisco'  ));
		App\Municipality::create(array( 'id' => 458, 'state_id' => 23, 'municipality'=> 'Santa Rita'  ));
		App\Municipality::create(array( 'id' => 459, 'state_id' => 23, 'municipality'=> 'Simón Bolívar'  ));
		App\Municipality::create(array( 'id' => 460, 'state_id' => 23, 'municipality'=> 'Sucre'  ));
		App\Municipality::create(array( 'id' => 461, 'state_id' => 23, 'municipality'=> 'Valmore Rodríguez'  ));
		App\Municipality::create(array( 'id' => 462, 'state_id' => 24, 'municipality'=> 'Libertador'  ));
    }
}
